name: Elementary
version: 0.1
css_directory: elementary/css
files_directory: files
jscripts_directory: elementary/js
resources_directory: resources
template_directoy: templates
jscirpts:
  - elementary.js
  
styleshets:
  - elementary.css
require:
  -
    name: jquery
    public: true
    load_order: 1
    vendor_dir: components/jquery/
    copy_all: false
    js:
      - jquery.js
  -
    name: bootstrap
    public: true
    load_order: 2
    vendor_dir: twbs/bootstrap/dist
    copy_all: false
    css: 
      - /css/bootstrap.css
    js:
      - /js/bootstrap.js
layout:
  container_class: container-fluid
  regions:
    -
      name: header
      render_order: 1
      class: header col-12
      id: header
      template: 
      wrapper: header
    -
      name: navigation
      render_order: 2
      class: nav col-2
      id: nav
      template:
      wrapper: nav
    -
      name: content
      render_order: 3
      class: content col-10
      id: content
      template:
      wrapper: section
    -
      name: footer
      render_order: 4
      class: footer col-12
      id: footer
      template:
      wrapper: footer
